CREATE TABLE ORDERS (
  ID INT NOT NULL,
  ORDER_NUMBER INT,
  CUSTOMER_ID INT,
  PRODUCT_ID INT,
  PRIMARY KEY (ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
)

SELECT
  ORDERS.ORDER_NUMBER,
  CUSTOMERS.FIRST_NAME,
  CUSTOMERS.LAST_NAME,
  CUSTOMERS.ADDRESS
FROM
  ORDERS
  INNER JOIN CUSTOMERS
  ON CUSTOMER_ID = CUSTOMERS.ID

SELECT
  ORDERS.ORDER_NUMBER,
  PRODUCTS.NAME,
  PRODUCTS.PRICE,
  PRODUCTS.STOCK
FROM
  ORDERS
  INNER JOIN PRODUCTS
  ON ORDERS.PRODUCT_ID = PRODUCTS.ID  